# command line: main.py train-causal-net -c ./config/exp9/train0.yaml

base_lr: 0.001
batch_size: 4
branch_loss_weight: 0.33
clf_only_epoch: 1
config: ./config/exp9/train0.yaml
debug: false
device:
- 0
eval_interval: 1
feeder: feeder.feeder_image_causal.Feeder
ignore_weights: []
log_interval: 1000
loss: clf
loss_weight:
- 0.03793475268422502
- 0.02297650729558594
- 0.13503716619253006
- 0.0678856566027347
- 0.028734972928328897
- 0.12262549325502432
- 0.27594750848857486
- 0.10352619987152427
lr_decay: 0.3
model: net.causal_net.CAUSAL_NET
model_args:
    backbone: resnet34
    d_in: 512
    d_m: 256
    d_out: 512
    num_class: 8
    pooling: true
    subject: true
    temporal_model: single
nesterov: true
num_epoch: 15
num_worker: 0
optimizer: SGD
pavi_log: false
phase: train
pretrain: true
print_log: true
resume: ''
save_interval: 5
save_log: true
save_result: false
seed: 42
start_epoch: 0
step: []
test_batch_size: 4
test_feeder_args:
    image_path: /home/hfut1609/Disk_sda/hzy/faceAU/CIS/data/DISFA/list_random2.1/test0_imagepath.pkl
    image_size: 256
    istrain: false
    label_path: /home/hfut1609/Disk_sda/hzy/faceAU/CIS/data/DISFA/list_random2.1/test0_label.pkl
train_feeder_args:
    image_path: /home/hfut1609/Disk_sda/hzy/faceAU/CIS/data/DISFA/list_random2.1/train0_imagepath.pkl
    image_size: 256
    istrain: true
    label_path: /home/hfut1609/Disk_sda/hzy/faceAU/CIS/data/DISFA/list_random2.1/train0_label.pkl
use_gpu: true
weight_decay: 0.0005
weights: null
work_dir: ./work_dir/train/disfa/exp9/0
