# command line: main.py train-image-causal -c ./config/exp1/train0.yaml

backbone_only: true
base_lr: 0.001
batch_size: 64
clf_only_epoch: 1
config: ./config/exp1/train0.yaml
debug: false
device:
- 0
eval_interval: 1
feeder: feeder.feeder_image_causal.Feeder
ignore_weights: []
log_interval: 1000
loss: clf
loss_weight:
- 0.05919846932306735
- 0.045562996346200396
- 0.15979898339077214
- 0.09075715487730379
- 0.05117624684470776
- 0.1350522712341083
- 0.31323551447112113
- 0.07716778662732397
lr_decay: 0.3
model: net.CISNet.Model
model_args:
    backbone: resnet34
    d_in: 512
    d_m: 256
    d_out: 512
    num_class: 8
    pooling: true
    subject: true
    temporal_model: single
nesterov: true
num_epoch: 15
num_worker: 0
optimizer: SGD
pavi_log: false
phase: train
pretrain: true
print_log: true
resume: ''
save_interval: 5
save_log: true
save_result: false
seed: 42
start_epoch: 0
step: []
test_batch_size: 64
test_feeder_args:
    image_path: /home/hfut1609/Disk_sda/hzy/faceAU/CIS/data/DISFA/list_random1/test0_imagepath.pkl
    image_size: 256
    istrain: false
    label_path: /home/hfut1609/Disk_sda/hzy/faceAU/CIS/data/DISFA/list_random1/test0_label.pkl
train_feeder_args:
    image_path: /home/hfut1609/Disk_sda/hzy/faceAU/CIS/data/DISFA/list_random1/train0_imagepath.pkl
    image_size: 256
    istrain: true
    label_path: /home/hfut1609/Disk_sda/hzy/faceAU/CIS/data/DISFA/list_random1/train0_label.pkl
use_gpu: true
weight_decay: 0.0005
weights: null
work_dir: ./work_dir/train/disfa/exp1/0
