# command line: main.py train-image-causal -c ./config/exp4/train1.yaml

backbone_only: true
base_lr: 0.001
batch_size: 4
clf_only_epoch: 1
config: ./config/exp4/train1.yaml
debug: false
device:
- 0
eval_interval: 1
feeder: feeder.feeder_image_causal.Feeder
ignore_weights: []
log_interval: 1000
loss: clf
loss_weight:
- 0.04851369886697634
- 0.03520095897831925
- 0.161700803374866
- 0.07988796551366428
- 0.04619693634089835
- 0.12156663861962448
- 0.2541638331469934
- 0.09405364284973317
lr_decay: 0.3
model: net.CISNet.Model
model_args:
    backbone: resnet34
    d_in: 512
    d_m: 256
    d_out: 512
    num_class: 8
    pooling: true
    subject: true
    temporal_model: single
nesterov: true
num_epoch: 20
num_worker: 0
optimizer: SGD
pavi_log: false
phase: train
pretrain: true
print_log: true
resume: ''
save_interval: 5
save_log: true
save_result: false
seed: 42
start_epoch: 0
step: []
test_batch_size: 4
test_feeder_args:
    image_path: /home/hfut1609/Disk_sda/hzy/faceAU/CIS/data/DISFA/list_random3/test1_imagepath.pkl
    image_size: 256
    istrain: false
    label_path: /home/hfut1609/Disk_sda/hzy/faceAU/CIS/data/DISFA/list_random3/test1_label.pkl
train_feeder_args:
    image_path: /home/hfut1609/Disk_sda/hzy/faceAU/CIS/data/DISFA/list_random3/train1_imagepath.pkl
    image_size: 256
    istrain: true
    label_path: /home/hfut1609/Disk_sda/hzy/faceAU/CIS/data/DISFA/list_random3/train1_label.pkl
use_gpu: true
weight_decay: 0.0005
weights: null
work_dir: ./work_dir/train/disfa/exp4/1
