# command line: main.py train-causal-net -c ./config/exp11/train2.yaml

base_lr: 0.001
batch_size: 4
branch_loss_weight: 0.33
clf_only_epoch: 1
config: ./config/exp11/train2.yaml
debug: false
device:
- 0
eval_interval: 1
feeder: feeder.feeder_image_causal.Feeder
ignore_weights: []
log_interval: 1000
loss: clf
loss_class_weight:
- 0.05837696990955328
- 0.051562147671184826
- 0.18123167890161102
- 0.09980457495051738
- 0.05330343497106206
- 0.15449853431212887
- 0.31815448600706536
- 0.08306817327687721
loss_weight:
- 0.05369158447783206
- 0.0474237256890036
- 0.16668586966540694
- 0.09179417457830215
- 0.04902525578394322
- 0.14209835007834823
- 0.2926191354041847
- 0.07640105078809106
lr_decay: 0.3
model: net.causal_net.CAUSAL_NET
model_args:
    backbone: resnet34
    d_in: 512
    d_m: 256
    d_out: 512
    num_class: 8
    pooling: true
    subject: true
    temporal_model: single
nesterov: true
num_epoch: 20
num_worker: 0
optimizer: SGD
pavi_log: false
phase: train
pretrain: true
print_log: true
resume: ''
save_interval: 5
save_log: true
save_result: false
seed: 42
start_epoch: 0
step: []
test_batch_size: 4
test_feeder_args:
    image_path: /home/hfut1609/Disk_sda/hzy/faceAU/CIS/data/DISFA/list_random2.1/test2_imagepath.pkl
    image_size: 256
    istrain: false
    label_path: /home/hfut1609/Disk_sda/hzy/faceAU/CIS/data/DISFA/list_random2.1/test2_label.pkl
train_feeder_args:
    image_path: /home/hfut1609/Disk_sda/hzy/faceAU/CIS/data/DISFA/list_random2.1/train2_imagepath.pkl
    image_size: 256
    istrain: true
    label_path: /home/hfut1609/Disk_sda/hzy/faceAU/CIS/data/DISFA/list_random2.1/train2_label.pkl
use_gpu: true
weight_decay: 0.0005
weights: null
work_dir: ./work_dir/train/disfa/exp11/2
